apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: was-liberty-app
    app.kubernetes.io/name: was-liberty-app
    app.kubernetes.io/part-of: was-liberty-app
    liberty.websphere.ibm.com/name: was-liberty-app
    environment: base
  name: was-liberty-app
